name: 'IIIF Action'
description: 'Creates IIIF derivates'
inputs:
  cmd:
    description: 'The command to run'
    required: true
runs:
  env:
    DOCKER_BUILDKIT: 1
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.cmd }}
