name: Publish Docker image
on:
  push:
    branches:
      - main

jobs:
#  tag-snapshot:
#    name: Add a tag to satisfy stupid action runner
#    runs-on: ubuntu-latest
#    steps:
#    - name: Tag commit
#      uses: tvdias/github-tagger@v0.0.1
#      with:
#        repo-token: "${{ secrets.GITHUB_TOKEN }}"
#        tag: "latest"


  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0
      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
          logout: false
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ghcr.io/cmahnke/iiif-action:latest

  build_uploader:
    name: Push uploader Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0
      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
          logout: false
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          build-args: ADDITIONAL_DEPS=parallel rsync sshpass imagemagick
          push: true
          tags: |
            ghcr.io/cmahnke/iiif-action:latest-uploader

  build_jxl:
    name: Push JPEG XL Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0
      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
          logout: false
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          build-args: GIT_TAG=add-jxl
          push: true
          tags: |
            ghcr.io/cmahnke/iiif-action:latest-jxl

  test:
    name: Test the build Docker image
    needs: push_to_registry
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0
      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
          logout: false
#      - name: Create IIIF derivates
#        uses: docker://ghcr.io/cmahnke/iiif-action:latest
#        with:
#          args: 'vips dzsave test/2010_02-March-April_Whaling_01.jpg test/  -t 512 --layout iiif --id ''.'''
      - name: Create IIIF derivates
        run: docker run -v ${PWD}:${PWD} ghcr.io/cmahnke/iiif-action:latest sh -c "vips dzsave ${PWD}/test/2010_02-March-April_Whaling_01.jpg ${PWD}/test/ -t 512 --layout iiif --id '.'"
      - name: List results
        run: |
          ls test
          ls test/test
