name: Publish Docker image
on:
  push:
    branches:
      - main

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v2
        env:
          DOCKER_BUILDKIT: 1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: cmahnke/iiif-action/iiif-action
          tag_with_ref: true
